name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gym-search
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: build page
      run: yarn run build && yarn run export && touch ./out/.nojekyll
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: gym-search/out
